### ISSUE TITLE
supervisor-integration still broken

### ISSUE THREAD

**Issue by pbauer** [kitconcept/kitconcept.recipe.solr#12]
Starting works with `./bin/solr-foreground` but stopping does not. 
The pid-file it looks for (`./bin/solr-8983.pid') when stopping does not exists. 
Instead it is in `./var/solr/solr.pid`

@gforcada: Can you confirm this? 

```
supervisor> status
memmon                           RUNNING   pid 49643, uptime 0:01:52
solr                             RUNNING   pid 49845, uptime 0:00:50
zeoclient1                       RUNNING   pid 49646, uptime 0:01:52
zeoclient2                       RUNNING   pid 49647, uptime 0:01:52
zeoserver                        RUNNING   pid 49644, uptime 0:01:52

supervisor> stop solr
solr: stopped

supervisor> start solr
solr: ERROR (spawn error)

supervisor> status
memmon                           RUNNING   pid 49643, uptime 0:02:18
solr                             FATAL     Exited too quickly (process log may have details)
zeoclient1                       RUNNING   pid 49646, uptime 0:02:18
zeoclient2                       RUNNING   pid 49647, uptime 0:02:18
zeoserver                        RUNNING   pid 49644, uptime 0:02:18
```

```
==> var/log/supervisord.log <==
2019-11-15 14:52:57,821 INFO spawned: 'solr' with pid 50399

==> var/log/solr-stdout---supervisor-fprsl1k0.log <==
Java HotSpot(TM) 64-Bit Server VM warning: -XX:+UseLargePages not supported in this VM
2019-11-15 13:52:59.518 INFO  (main) [   ] o.e.j.u.log Logging initialized @1193ms to org.eclipse.jetty.util.log.Slf4jLog
2019-11-15 13:52:59.622 WARN  (main) [   ] o.e.j.x.XmlConfiguration Deprecated method public void org.eclipse.jetty.rewrite.handler.RedirectRegexRule.setReplacement(java.lang.String) in file:///Users/pbauer/workspace/dipf-intranet/parts/solr/server/etc/jetty.xml
2019-11-15 13:52:59.669 WARN  (main) [   ] o.e.j.s.AbstractConnector Ignoring deprecated socket close linger time
2019-11-15 13:52:59.670 WARN  (main) [   ] o.e.j.x.XmlConfiguration Deprecated method public void org.eclipse.jetty.server.ServerConnector.setSoLingerTime(int) in file:///Users/pbauer/workspace/dipf-intranet/parts/solr/server/etc/jetty-http.xml
2019-11-15 13:52:59.674 INFO  (main) [   ] o.e.j.s.Server jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 11.0.1+13-LTS
2019-11-15 13:52:59.690 INFO  (main) [   ] o.e.j.d.p.ScanningAppProvider Deployment monitor [file:///Users/pbauer/workspace/dipf-intranet/parts/solr/server/contexts/] at interval 0
2019-11-15 13:52:59.967 INFO  (main) [   ] o.e.j.w.StandardDescriptorProcessor NO JSP Support for /solr, did not find org.apache.jasper.servlet.JspServlet
2019-11-15 13:52:59.978 INFO  (main) [   ] o.e.j.s.session DefaultSessionIdManager workerName=node0
2019-11-15 13:52:59.978 INFO  (main) [   ] o.e.j.s.session No SessionScavenger set, using defaults
2019-11-15 13:52:59.979 INFO  (main) [   ] o.e.j.s.session node0 Scavenging every 660000ms

==> var/log/supervisord.log <==
2019-11-15 14:52:59,320 INFO success: solr entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

==> var/log/solr-stdout---supervisor-fprsl1k0.log <==
2019-11-15 13:53:00.091 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter Using logger factory org.apache.logging.slf4j.Log4jLoggerFactory
2019-11-15 13:53:00.095 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter  ___      _       Welcome to Apache Solr™ version 8.2.0
2019-11-15 13:53:00.095 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter / __| ___| |_ _   Starting in standalone mode on port 8983
2019-11-15 13:53:00.095 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter \__ \/ _ \ | '_|  Install dir: /Users/pbauer/workspace/dipf-intranet/parts/solr
2019-11-15 13:53:00.095 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter |___/\___/_|_|    Start time: 2019-11-15T13:53:00.095692Z
2019-11-15 13:53:00.137 INFO  (main) [   ] o.a.s.c.SolrResourceLoader Using system property solr.solr.home: /Users/pbauer/workspace/dipf-intranet/parts/solr/server/solr
2019-11-15 13:53:00.142 INFO  (main) [   ] o.a.s.c.SolrXmlConfig Loading container configuration from /Users/pbauer/workspace/dipf-intranet/parts/solr/server/solr/solr.xml
2019-11-15 13:53:00.192 INFO  (main) [   ] o.a.s.c.SolrXmlConfig MBean server found: com.sun.jmx.mbeanserver.JmxMBeanServer@148080bb, but no JMX reporters were configured - adding default JMX reporter.
2019-11-15 13:53:00.655 INFO  (main) [   ] o.a.s.h.c.HttpShardHandlerFactory Host whitelist initialized: WhitelistHostChecker [whitelistHosts=null, whitelistHostCheckingEnabled=true]
2019-11-15 13:53:01.031 WARN  (main) [   ] o.e.j.u.s.S.config Trusting all certificates configured for Client@7a1f8def[provider=null,keyStore=null,trustStore=null]
2019-11-15 13:53:01.033 WARN  (main) [   ] o.e.j.u.s.S.config No Client EndPointIdentificationAlgorithm configured for Client@7a1f8def[provider=null,keyStore=null,trustStore=null]
2019-11-15 13:53:01.224 WARN  (main) [   ] o.e.j.u.s.S.config Trusting all certificates configured for Client@17b6d426[provider=null,keyStore=null,trustStore=null]
2019-11-15 13:53:01.224 WARN  (main) [   ] o.e.j.u.s.S.config No Client EndPointIdentificationAlgorithm configured for Client@17b6d426[provider=null,keyStore=null,trustStore=null]
2019-11-15 13:53:01.557 INFO  (main) [   ] o.a.s.c.TransientSolrCoreCacheDefault Allocating transient cache for 2147483647 transient cores
2019-11-15 13:53:01.562 INFO  (main) [   ] o.a.s.h.a.MetricsHistoryHandler No .system collection, keeping metrics history in memory.
2019-11-15 13:53:01.678 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.node' (registry 'solr.node') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@148080bb
2019-11-15 13:53:01.679 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.jvm' (registry 'solr.jvm') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@148080bb
2019-11-15 13:53:01.694 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.jetty' (registry 'solr.jetty') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@148080bb
2019-11-15 13:53:01.742 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Found 1 core definitions underneath /Users/pbauer/workspace/dipf-intranet/parts/solr/server/solr
2019-11-15 13:53:01.743 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Cores are: [plone]
2019-11-15 13:53:01.770 INFO  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.c.SolrConfig Using Lucene MatchVersion: 4.5.0
2019-11-15 13:53:01.879 INFO  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.IndexSchema [plone] Schema name=plone
2019-11-15 13:53:01.881 INFO  (main) [   ] o.e.j.s.h.ContextHandler Started o.e.j.w.WebAppContext@5bd73d1a{/solr,file:///Users/pbauer/workspace/dipf-intranet/parts/solr/server/solr-webapp/webapp/,AVAILABLE}{/Users/pbauer/workspace/dipf-intranet/parts/solr/server/solr-webapp/webapp}
2019-11-15 13:53:01.895 INFO  (main) [   ] o.e.j.s.AbstractConnector Started ServerConnector@274872f8{HTTP/1.1,[http/1.1, h2c]}{0.0.0.0:8983}
2019-11-15 13:53:01.896 INFO  (main) [   ] o.e.j.s.Server Started @3580ms
2019-11-15 13:53:01.911 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.c.SolrResourceLoader Solr loaded a deprecated plugin/analysis class [solr.TrieLongField]. Please consult documentation how to replace it accordingly.
2019-11-15 13:53:01.923 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.c.SolrResourceLoader Solr loaded a deprecated plugin/analysis class [solr.TrieDateField]. Please consult documentation how to replace it accordingly.
2019-11-15 13:53:01.929 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.c.SolrResourceLoader Solr loaded a deprecated plugin/analysis class [solr.TrieFloatField]. Please consult documentation how to replace it accordingly.
2019-11-15 13:53:01.935 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.c.SolrResourceLoader Solr loaded a deprecated plugin/analysis class [solr.TrieIntField]. Please consult documentation how to replace it accordingly.
2019-11-15 13:53:01.970 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.c.SolrResourceLoader Solr loaded a deprecated plugin/analysis class [solr.TrieDoubleField]. Please consult documentation how to replace it accordingly.
2019-11-15 13:53:02.071 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenizerFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.085 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.129 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.131 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.134 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenizerFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.134 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.135 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.138 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader CharFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.143 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenizerFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.144 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.144 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.144 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.146 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.149 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader CharFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.149 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenizerFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.149 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.150 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.150 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.151 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.151 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.153 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.162 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenizerFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.163 WARN  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.FieldTypePluginLoader TokenFilterFactory is using deprecated 4.5.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
2019-11-15 13:53:02.217 INFO  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.IndexSchema Loaded schema plone/1.5 with uniqueid field UID
2019-11-15 13:53:02.382 INFO  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.c.CoreContainer Creating SolrCore 'plone' using configuration from instancedir /Users/pbauer/workspace/dipf-intranet/parts/solr/server/solr/plone, trusted=true
2019-11-15 13:53:02.408 INFO  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.core.plone' (registry 'solr.core.plone') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@148080bb
2019-11-15 13:53:02.420 INFO  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.c.SolrCore [[plone] ] Opening new SolrCore at [/Users/pbauer/workspace/dipf-intranet/parts/solr/server/solr/plone], dataDir=[/Users/pbauer/workspace/dipf-intranet/parts/solr/server/solr/plone/data/]
2019-11-15 13:53:02.812 INFO  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.u.UpdateHandler Using UpdateLog implementation: org.apache.solr.update.UpdateLog
2019-11-15 13:53:02.812 INFO  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.u.UpdateLog Initializing UpdateLog: dataDir= defaultSyncLevel=FLUSH numRecordsToKeep=100 maxNumLogsToKeep=10 numVersionBuckets=65536
2019-11-15 13:53:02.837 INFO  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.u.CommitTracker Hard AutoCommit: if uncommitted for 15000ms;
2019-11-15 13:53:02.837 INFO  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.u.CommitTracker Soft AutoCommit: disabled
2019-11-15 13:53:02.963 INFO  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.s.SolrIndexSearcher Opening [Searcher@2cbd30a6[plone] main]
2019-11-15 13:53:02.976 INFO  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.r.ManagedResourceStorage File-based storage initialized to use dir: /Users/pbauer/workspace/dipf-intranet/parts/solr/server/solr/plone/conf
2019-11-15 13:53:02.994 INFO  (coreLoadExecutor-9-thread-1) [   x:plone] o.a.s.h.ReplicationHandler Commits will be reserved for 10000ms.
2019-11-15 13:53:03.026 INFO  (searcherExecutor-10-thread-1-processing-x:plone) [   x:plone] o.a.s.c.SolrCore [plone] Registered new searcher Searcher@2cbd30a6[plone] main{ExitableDirectoryReader(UninvertingDirectoryReader(Uninverting(_0(8.2.0):C1000:[diagnostics={java.vendor=Oracle Corporation, os=Mac OS X, java.version=11.0.1, java.vm.version=11.0.1+13-LTS, lucene.version=8.2.0, os.arch=x86_64, java.runtime.version=11.0.1+13-LTS, source=flush, os.version=10.15.1, timestamp=1573824633852}]:[attributes={Lucene50StoredFieldsFormat.mode=BEST_SPEED}]) Uninverting(_1(8.2.0):C1000:[diagnostics={java.vendor=Oracle Corporation, os=Mac OS X, java.version=11.0.1, java.vm.version=11.0.1+13-LTS, lucene.version=8.2.0, os.arch=x86_64, java.runtime.version=11.0.1+13-LTS, source=flush, os.version=10.15.1, timestamp=1573824666583}]:[attributes={Lucene50StoredFieldsFormat.mode=BEST_SPEED}]) Uninverting(_2(8.2.0):C577:[diagnostics={java.vendor=Oracle Corporation, os=Mac OS X, java.version=11.0.1, java.vm.version=11.0.1+13-LTS, lucene.version=8.2.0, os.arch=x86_64, java.runtime.version=11.0.1+13-LTS, source=flush, os.version=10.15.1, timestamp=1573824686402}]:[attributes={Lucene50StoredFieldsFormat.mode=BEST_SPEED}])))}
Traceback (most recent call last):
  File "/Users/pbauer/workspace/dipf-intranet/bin/solr-foreground", line 15, in <module>
    sys.exit(kitconcept.recipe.solr.solr_foreground({'recipe': 'kitconcept.recipe.solr', 'src': 'http://archive.apache.org/dist/lucene/solr/8.2.0/solr-8.2.0.tgz', 'solr-config': '/Users/pbauer/workspace/dipf-intranet/solr_config', 'eggs-directory': '/Users/pbauer/.cache/buildout/eggs', '_e': '/Users/pbauer/.cache/buildout/eggs', 'develop-eggs-directory': '/Users/pbauer/workspace/dipf-intranet/develop-eggs', '_d': '/Users/pbauer/workspace/dipf-intranet/develop-eggs', 'bin-directory': '/Users/pbauer/workspace/dipf-intranet/bin', '_b': '/Users/pbauer/workspace/dipf-intranet/bin', 'port': '8983', 'solr-core-name': 'plone', 'executable': '/Users/pbauer/workspace/dipf-intranet/bin/python3.7'}))
  File "/Users/pbauer/.cache/buildout/eggs/kitconcept.recipe.solr-1.0.0a3-py3.7.egg/kitconcept/recipe/solr/__init__.py", line 168, in solr_foreground
    return os.waitpid(process.pid, 0)
  File "/Users/pbauer/.cache/buildout/eggs/kitconcept.recipe.solr-1.0.0a3-py3.7.egg/kitconcept/recipe/solr/__init__.py", line 158, in exit_handler
    with open(filepath) as pidfile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/pbauer/workspace/dipf-intranet/bin/solr-8983.pid'

==> var/log/supervisord.log <==
2019-11-15 14:53:27,820 INFO waiting for solr to stop
2019-11-15 14:53:27,850 INFO stopped: solr (exit status 1)
```

```
$ ./bin/solr-status

Found 1 Solr nodes:

Solr process 50402 running on port 8983
{
  "solr_home":"/Users/pbauer/workspace/dipf-intranet/parts/solr/server/solr",
  "version":"8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:11:04",
  "startTime":"2019-11-15T13:52:58.548Z",
  "uptime":"0 days, 0 hours, 6 minutes, 2 seconds",
  "memory":"257.2 MB (%50.2) of 512 MB"}

$ ./bin/solr-stop

No Solr nodes found to stop.
```

**Comment by gforcada** [comment]
@pbauer oh, I see, I attempted to fix that on #7 some time ago. 

Which version are you using? When I fixed it on #7 there was no release (IIRC), I see that at least there is one commit on top of my changes, that might be the problem? if you use a git checkout, could you try to checkout this commit https://github.com/kitconcept/kitconcept.recipe.solr/commit/0cb45f0080f0a144f3e74e671bc64c0d8ddc3b2d#diff-ad3cd01c96a112284d76690762db7e93 and see if that makes it work again. If that's the case, you already know where's the problem. If not, blame it on me :)

**Comment by pbauer** [comment]
@gforcada I'm sorry to say I have to blame you, your revision produces the same errors.

**Comment by gforcada** [comment]
No worries, but that's a bit surprising, as I guess I had tested it... :sweat_smile: #7 is from January, almost a year ago. If nobody ever had this problem, it might be that nobody actually cares of using it, now that I mention it, my muscle memory when working with Plone +Solr is to open three tabs: `./bin/instance fg`, `./bin/zeo fg` and `./bin/solr-start`.

So I guess that although I tried (and clearly failed) at fixing it, I myself gave up on it.

I remember trying to port over the logic from https://github.com/collective/collective.recipe.solrinstance

I'm afraid though, that I have the least of interest in working on this, given the results of my contributions, I'm sorry for you.

**Comment by tisto** [comment]
> I'm afraid though, that I have the least of interest in working on this, given the results of my contributions, I'm sorry for you.

@gforcada would you mind elaborating on this?

I merged every single PR that you opened on this repo:

https://github.com/kitconcept/kitconcept.recipe.solr/pulls?q=is%3Apr+is%3Aclosed

I merged #7 seven days after you opened it.

**Comment by gforcada** [comment]
No, I don't want to waste more time
